import Head from 'next/head'
import Image from 'next/image'
import Avatar from '../components/Avatar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google v2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */} 
      <header className="flex w-full p-5 justify-between text-sm text-gray-700">
        {/* Left */} 
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>
        {/* Right */} 
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>
          {/* Icon */} 
          <Avatar url="https://media-exp1.licdn.com/dms/image/C5103AQGYKpOql95-Sw/profile-displayphoto-shrink_200_200/0/1517339551606?e=1640822400&v=beta&t=0BRLWGBlDGczdAC_vFjU4GUmuJQzg77R-MnQd7E8t84"/>
        </div>
      </header>

      {/* Body */} 

      {/* Footer */} 
    </div>
  )
}
